from src.filter import filter_word

data_1 = [
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93353083",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93353083",
        "archived": False,
        "area": {"id": "26", "name": "Воронеж", "url": "https://api.hh.ru/areas/26"},
        "branding": {"tariff": "BASIC", "type": "CONSTRUCTOR"},
        "contacts": None,
        "created_at": "2024-02-16T14:58:28+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/3499705",
            "id": "3499705",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/6479866.png",
                "90": "https://hhcdn.ru/employer-logo/6479865.png",
                "original": "https://hhcdn.ru/employer-logo-original/1214854.png",
            },
            "name": "Специализированный застройщик BM GROUP",
            "trusted": True,
            "url": "https://api.hh.ru/employers/3499705",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3499705",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "93353083",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Тестировщик комфорта квартир",
        "premium": False,
        "professional_roles": [{"id": "107", "name": "Руководитель проектов"}],
        "published_at": "2024-02-16T14:58:28+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 350000, "gross": False, "to": 450000},
        "schedule": {"id": "flexible", "name": "Гибкий график"},
        "show_logo_in_search": True,
        "snippet": {
            "requirement": "Занимать активную жизненную позицию, уметь "
            "активно танцевать и громко петь. Обладать "
            "навыками коммуникации, чтобы налаживать "
            "добрососедские отношения. Обладать системным "
            "мышлением...",
            "responsibility": "Оценивать вид из окна: встречать рассветы на "
            "кухне, и провожать алые закаты в спальне. "
            "Оценивать инфраструктуру района: ежедневно "
            "ходить на...",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93353083?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92223756",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223756",
        "archived": False,
        "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
        "contacts": None,
        "created_at": "2024-01-25T17:37:04+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/9498120",
            "id": "9498120",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
            },
            "name": "Яндекс Команда для бизнеса",
            "trusted": True,
            "url": "https://api.hh.ru/employers/9498120",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "92223756",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Удаленный диспетчер чатов (в Яндекс)",
        "premium": False,
        "professional_roles": [{"id": "40", "name": "Другое"}],
        "published_at": "2024-01-25T17:37:04+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 30000, "gross": True, "to": 44000},
        "schedule": {"id": "remote", "name": "Удаленная работа"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Способен работать в команде. Способен принимать "
            "решения самостоятельно. Готов учиться и узнавать "
            "новое. Опыт работы в колл-центре или службе...",
            "responsibility": "Работать с клиентами или партнерами для "
            "решения разнообразных ситуаций. Совершать "
            "звонки по их обращениям и давать письменные "
            "ответы. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92223756?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92223870",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223870",
        "archived": False,
        "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
        "contacts": None,
        "created_at": "2024-01-25T17:39:01+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/9498120",
            "id": "9498120",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
            },
            "name": "Яндекс Команда для бизнеса",
            "trusted": True,
            "url": "https://api.hh.ru/employers/9498120",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "92223870",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Удаленный специалист службы поддержки (в Яндекс)",
        "premium": False,
        "professional_roles": [{"id": "40", "name": "Другое"}],
        "published_at": "2024-01-25T17:39:01+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 30000, "gross": True, "to": 44000},
        "schedule": {"id": "remote", "name": "Удаленная работа"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Способен работать в команде. Способен принимать "
            "решения самостоятельно. Готов учиться и узнавать "
            "новое. Опыт работы в колл-центре или службе...",
            "responsibility": "Работать с клиентами или партнерами для "
            "решения разнообразных ситуаций. Совершать "
            "звонки по их обращениям и давать письменные "
            "ответы. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92223870?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92752367",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92752367",
        "archived": False,
        "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
        "contacts": None,
        "created_at": "2024-02-06T11:30:02+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/1418491",
            "id": "1418491",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/2935217.jpeg",
                "90": "https://hhcdn.ru/employer-logo/2935216.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/623516.jpg",
            },
            "name": "Витрина Недвижимости",
            "trusted": True,
            "url": "https://api.hh.ru/employers/1418491",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=1418491",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "92752367",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер по продажам недвижимости",
        "premium": False,
        "professional_roles": [{"id": "6", "name": "Агент по недвижимости"}],
        "published_at": "2024-02-06T11:30:02+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "KZT", "from": 500000, "gross": True, "to": 1000000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Отличные коммуникативные навыки, способность "
            "найти подход к каждому клиенту. Навыки "
            "проведения деловых переговоров. Наличие "
            "амбициозных целей и успешный опыт их...",
            "responsibility": "Анализ рынка и объектов недвижимости. "
            "Предварительная оценка недвижимости. Подбор "
            "объектов недвижимости в интересах клиентов. "
            "Консультирование клиентов по купле-продаже "
            "объектов...",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92752367?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92223673",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223673",
        "archived": False,
        "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
        "contacts": None,
        "created_at": "2024-01-25T17:34:32+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/9498120",
            "id": "9498120",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
            },
            "name": "Яндекс Команда для бизнеса",
            "trusted": True,
            "url": "https://api.hh.ru/employers/9498120",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "92223673",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер чатов, удалённо (в Яндекс)",
        "premium": False,
        "professional_roles": [{"id": "40", "name": "Другое"}],
        "published_at": "2024-01-25T17:34:32+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 30000, "gross": True, "to": 44000},
        "schedule": {"id": "remote", "name": "Удаленная работа"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Способен работать в команде. Способен принимать "
            "решения самостоятельно. Готов учиться и узнавать "
            "новое. Опыт работы в колл-центре или службе...",
            "responsibility": "Работать с клиентами или партнерами для "
            "решения разнообразных ситуаций. Совершать "
            "звонки по их обращениям и давать письменные "
            "ответы. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92223673?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93209001",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93209001",
        "archived": False,
        "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
        "contacts": None,
        "created_at": "2024-02-14T12:32:06+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/4621904",
            "id": "4621904",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/3387666.png",
                "90": "https://hhcdn.ru/employer-logo/3387665.png",
                "original": "https://hhcdn.ru/employer-logo-original/736672.png",
            },
            "name": "«MY FREIGHTER» LLC",
            "trusted": True,
            "url": "https://api.hh.ru/employers/4621904",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=4621904",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "93209001",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Бортпроводник",
        "premium": False,
        "professional_roles": [{"id": "159", "name": "Бортпроводник"}],
        "published_at": "2024-02-14T12:32:06+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": None,
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Образование: среднее полное (11 классов), "
            "среднее специальное, высшее. Обязательное "
            "владение узбекским, русским и английским "
            "языками. Готовность работать согласно графику "
            "полетов. ",
            "responsibility": "Обеспечение безопасности на борту. Встреча и "
            "размещение пассажиров на борту. Инструктаж "
            "перед взлетом. Организация питания пассажиров "
            "во время полета. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93209001?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92195003",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92195003",
        "archived": False,
        "area": {"id": "1002", "name": "Минск", "url": "https://api.hh.ru/areas/1002"},
        "contacts": None,
        "created_at": "2024-01-25T11:58:58+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/3814315",
            "id": "3814315",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/3116885.jpeg",
                "90": "https://hhcdn.ru/employer-logo/3116884.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/668938.jpg",
            },
            "name": "ПроТекст",
            "trusted": True,
            "url": "https://api.hh.ru/employers/3814315",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3814315",
        },
        "employment": {"id": "part", "name": "Частичная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "92195003",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Наборщик текста/верстальщик",
        "premium": False,
        "professional_roles": [{"id": "84", "name": "Оператор ПК, оператор базы данных"}],
        "published_at": "2024-01-25T11:58:58+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "BYR", "from": 800, "gross": False, "to": None},
        "schedule": {"id": "remote", "name": "Удаленная работа"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "уверенное владение ПЭВМ (программы OCR - "
            "FineReader и аналоги, глубокое знание функций MS "
            "Word - Вставка, Макет, Конструктор таблиц). - "
            "возможность и готовность...",
            "responsibility": "выполнение распознания документов в формате "
            ",pdf, .jpg, .png на русском / английском "
            "языке, макетирование и форматирование в MS "
            "Word. - ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92195003?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [
            {"id": "from_four_to_six_hours_in_a_day", "name": "Можно работать сменами по 4–6 часов в " "день"}
        ],
        "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": {
            "building": "1к10",
            "city": "Казань",
            "description": None,
            "id": "15161689",
            "lat": 55.724135,
            "lng": 49.098078,
            "metro": None,
            "metro_stations": [],
            "raw": "Казань, Приволжский район, жилой массив Отары, Дорожная " "улица, 1к10",
            "street": "Приволжский район, жилой массив Отары, Дорожная " "улица",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93166058",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93166058",
        "archived": False,
        "area": {"id": "88", "name": "Казань", "url": "https://api.hh.ru/areas/88"},
        "contacts": None,
        "created_at": "2024-02-13T19:21:57+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/1060821",
            "id": "1060821",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/874869.jpeg",
                "90": "https://hhcdn.ru/employer-logo/874868.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/85446.jpg",
            },
            "name": "Рост Развитие Решение",
            "trusted": True,
            "url": "https://api.hh.ru/employers/1060821",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=1060821",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "93166058",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер по продажам (МЕРКАТОР)",
        "premium": False,
        "professional_roles": [{"id": "70", "name": "Менеджер по продажам, менеджер по работе с " "клиентами"}],
        "published_at": "2024-02-13T19:21:57+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 160000, "gross": True, "to": None},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Опыт в продажах. Опыт работы с клиентами. Умение " "проводить переговоры. Мобильность.",
            "responsibility": "Расширение клиентской базы. Проведение "
            "презентаций и переговоров. Заключение "
            "договоров. Отчетность в установленной форме.",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93166058?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/91178034",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=91178034",
        "archived": False,
        "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
        "contacts": None,
        "created_at": "2024-01-25T10:10:00+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/9522635",
            "id": "9522635",
            "logo_urls": None,
            "name": "IN-FIN-STROY INVEST",
            "trusted": True,
            "url": "https://api.hh.ru/employers/9522635",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9522635",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "91178034",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Оператор call-центра",
        "premium": False,
        "professional_roles": [{"id": "83", "name": "Оператор call-центра, специалист " "контактного центра"}],
        "published_at": "2024-01-25T10:10:00+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "UZS", "from": 3500000, "gross": True, "to": 20000000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": "Пожалуйста ознакомьтесь внимательно. Грамотная "
            "речь. Знание узбекского и русского языков. "
            "Отличное знание ПК. Коммуникабельность. "
            "Эмоциональная устойчивость. Вежливость, "
            "грамотность, любознательность, "
            "ответственность...",
            "responsibility": "Прием и обработка входящих звонков и "
            "исходящих звонков. Консультирование клиентов "
            "по телефону. Предоставление клиентам "
            "информации о компании. Осуществление "
            "исходящих информационных...",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/91178034?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": {
            "building": "5",
            "city": "Астана",
            "description": None,
            "id": "14393855",
            "lat": 51.133893,
            "lng": 71.382854,
            "metro": None,
            "metro_stations": [],
            "raw": "Астана, улица Анет баба, 5",
            "street": "улица Анет баба",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92818620",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92818620",
        "archived": False,
        "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
        "contacts": None,
        "created_at": "2024-02-07T11:34:26+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/10013830",
            "id": "10013830",
            "logo_urls": None,
            "name": "Агентство Недвижимости Абажур",
            "trusted": True,
            "url": "https://api.hh.ru/employers/10013830",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=10013830",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "92818620",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер по работе с клиентами",
        "premium": False,
        "professional_roles": [{"id": "70", "name": "Менеджер по продажам, менеджер по работе с " "клиентами"}],
        "published_at": "2024-02-07T11:34:26+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "KZT", "from": 418500, "gross": True, "to": 1000000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": "Не важно есть опыт у тебя или нет, я могу точно "
            "сказать, что ты сможешь зарабатывать в этой "
            "сфере!!! ",
            "responsibility": None,
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92818620?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": {
            "building": "166",
            "city": "Ташкент",
            "description": None,
            "id": "5906580",
            "lat": 41.295692,
            "lng": 69.218247,
            "metro": None,
            "metro_stations": [],
            "raw": "Ташкент, улица Мукими, 166",
            "street": "улица Мукими",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93119114",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93119114",
        "archived": False,
        "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
        "contacts": None,
        "created_at": "2024-02-13T08:39:43+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/3927191",
            "id": "3927191",
            "logo_urls": None,
            "name": "Научно информационный центр новых технологий при ГНК " "РУз",
            "trusted": True,
            "url": "https://api.hh.ru/employers/3927191",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3927191",
        },
        "employment": {"id": "probation", "name": "Стажировка"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "93119114",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Стажер",
        "premium": False,
        "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
        "published_at": "2024-02-13T08:39:43+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "UZS", "from": 2000000, "gross": False, "to": 2000000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": "Если вы , в том числе, студент по направлению IT "
            "или начинающий специалист, окончивший вуз, Вы "
            "можете принять участие в отборе...",
            "responsibility": "Комплексная оценка будет проводиться в форме "
            "собеседования. Стажировка по направлениям "
            "Java-backend и Mobile разработчик (flutter). "
            "Участие в непосредственной работе...",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93119114?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": {
            "building": "11",
            "city": "Санкт-Петербург",
            "description": None,
            "id": "11151437",
            "lat": 59.964485,
            "lng": 30.306571,
            "metro": None,
            "metro_stations": [],
            "raw": "Санкт-Петербург, Бармалеева улица, 11",
            "street": "Бармалеева улица",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92405436",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92405436",
        "archived": False,
        "area": {"id": "2", "name": "Санкт-Петербург", "url": "https://api.hh.ru/areas/2"},
        "contacts": None,
        "created_at": "2024-01-30T12:59:55+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/3474160",
            "id": "3474160",
            "logo_urls": None,
            "name": "Нордстрой",
            "trusted": True,
            "url": "https://api.hh.ru/employers/3474160",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3474160",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "92405436",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Хозработник",
        "premium": False,
        "professional_roles": [{"id": "32", "name": "Дворник"}],
        "published_at": "2024-01-30T12:59:55+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 65000, "gross": False, "to": 70000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": None,
            "responsibility": "Cезонныe pаботы: убоpкa cнега, лиcтьев, "
            "кoшeниe травы, мытьe дoрoжек. Убoрка мусоpа. "
            "Прoтиpание пыли, уборка в бapбекю, в "
            "бecедке. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92405436?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/87122346",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=87122346",
        "archived": False,
        "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
        "branding": {"tariff": None, "type": "MAKEUP"},
        "contacts": None,
        "created_at": "2024-02-20T11:00:11+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/2524051",
            "id": "2524051",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/3752460.png",
                "90": "https://hhcdn.ru/employer-logo/3752459.png",
                "original": "https://hhcdn.ru/employer-logo-original/827894.png",
            },
            "name": "Магазины Ароматный Мир формата food & wine",
            "trusted": True,
            "url": "https://api.hh.ru/employers/2524051",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=2524051",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "87122346",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Продавец-консультант",
        "premium": False,
        "professional_roles": [{"id": "97", "name": "Продавец-консультант, продавец-кассир"}],
        "published_at": "2024-02-20T11:00:11+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 70000, "gross": True, "to": 110000},
        "schedule": {"id": "shift", "name": "Сменный график"},
        "show_logo_in_search": True,
        "snippet": {
            "requirement": "Опыт работы не требуется, мы всему научим! Опыт "
            "работы в сетевых розничных магазинах "
            "приветствуется.",
            "responsibility": "Консультирование покупателей по ассортименту "
            "в магазине. Работа на современной и простой "
            "кассе. Выкладка продукции, оформление "
            "торгового зала рекламными материалами. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/87122346?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/77069438",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=77069438",
        "archived": False,
        "area": {"id": "160", "name": "Алматы", "url": "https://api.hh.ru/areas/160"},
        "contacts": None,
        "created_at": "2024-02-02T05:38:18+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/686727",
            "id": "686727",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/1107573.png",
                "90": "https://hhcdn.ru/employer-logo/1107572.png",
                "original": "https://hhcdn.ru/employer-logo-original/152128.png",
            },
            "name": "NurAi & Co",
            "trusted": True,
            "url": "https://api.hh.ru/employers/686727",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=686727",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "77069438",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер по туризму",
        "premium": False,
        "professional_roles": [{"id": "40", "name": "Другое"}],
        "published_at": "2024-02-02T05:38:18+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "KZT", "from": 180000, "gross": False, "to": 200000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "умение урегулировать форс-мажорные ситуации. - "
            "умение работать в системе Битрикс для ведения "
            "процесса бронирования. Требования: - опыт работы "
            "в туризме обязателен. - ",
            "responsibility": "консультирование клиентов по туристическим "
            "продуктам в офисе и по телефону. - обработка "
            "входящих заявок и ведение диалога с "
            "туристами. - ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/77069438?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/92210019",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92210019",
        "archived": False,
        "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
        "contacts": None,
        "created_at": "2024-01-25T14:24:55+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/9035038",
            "id": "9035038",
            "logo_urls": None,
            "name": "OOO UZGPS",
            "trusted": True,
            "url": "https://api.hh.ru/employers/9035038",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9035038",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "noExperience", "name": "Нет опыта"},
        "has_test": False,
        "id": "92210019",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Junior back-end developer",
        "premium": False,
        "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
        "published_at": "2024-01-25T14:24:55+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "UZS", "from": 4000000, "gross": True, "to": 8000000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": "Высшее профильное образование. Свободное "
            "владение русским и узбекским языками. Java Core. "
            "Spring/Spring Boot. Знание ООП и структуры "
            "данных. ",
            "responsibility": "Разрабатывать новые и поддерживать "
            "существующие продукты компании. Интегрировать "
            "сервисы и API. Написание микросервисов. "
            "Интеграции с внешними сервисами по REST, "
            "WebSocket. ",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/92210019?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": {
            "building": None,
            "city": None,
            "description": None,
            "id": "14977439",
            "lat": None,
            "lng": None,
            "metro": {
                "lat": 55.777201,
                "line_id": "7",
                "line_name": "Таганско-Краснопресненская",
                "lng": 37.517895,
                "station_id": "7.114",
                "station_name": "Полежаевская",
            },
            "metro_stations": [
                {
                    "lat": 55.777201,
                    "line_id": "7",
                    "line_name": "Таганско-Краснопресненская",
                    "lng": 37.517895,
                    "station_id": "7.114",
                    "station_name": "Полежаевская",
                },
                {
                    "lat": 55.777222,
                    "line_id": "95",
                    "line_name": "МЦК",
                    "lng": 37.507222,
                    "station_id": "95.539",
                    "station_name": "Хорошево",
                },
                {
                    "lat": 55.77643,
                    "line_id": "97",
                    "line_name": "Большая кольцевая линия",
                    "lng": 37.51981,
                    "station_id": "97.601",
                    "station_name": "Хорошевская",
                },
            ],
            "raw": None,
            "street": None,
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93523045",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93523045",
        "archived": False,
        "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
        "contacts": None,
        "created_at": "2024-02-20T11:07:12+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/827187",
            "id": "827187",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/4210365.jpeg",
                "90": "https://hhcdn.ru/employer-logo/4210364.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/942457.jpg",
            },
            "name": "BY business group",
            "trusted": True,
            "url": "https://api.hh.ru/employers/827187",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=827187",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
        "has_test": False,
        "id": "93523045",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер по сопровождению закупок (контрольно-измерительное " "оборудование)",
        "premium": False,
        "professional_roles": [{"id": "66", "name": "Менеджер по закупкам"}],
        "published_at": "2024-02-20T11:07:12+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 90000, "gross": False, "to": None},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Высшее или средне-специальное образование. Опыт "
            "работы на позиции менеджер по закупкам от 3 лет. "
            "Знание программы 1С (Управление...",
            "responsibility": "Получать и обрабатывать заявки. Обеспечивать "
            "своевременные поставки ТМЦ Заказчикам "
            "(закупка оборудования КИПиА и комплектующих). "
            "Контролировать поставки и своевременное "
            "выполнение обязанностей...",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93523045?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": {
            "building": "3",
            "city": "Астана",
            "description": None,
            "id": "816768",
            "lat": 51.125657,
            "lng": 71.421976,
            "metro": None,
            "metro_stations": [],
            "raw": "Астана, улица Сауран, 3",
            "street": "улица Сауран",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93514566",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93514566",
        "archived": False,
        "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
        "contacts": None,
        "created_at": "2024-02-20T09:52:02+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/2842834",
            "id": "2842834",
            "logo_urls": None,
            "name": "SNK CONSULT GROUP",
            "trusted": True,
            "url": "https://api.hh.ru/employers/2842834",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=2842834",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "93514566",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Водитель-помощник",
        "premium": False,
        "professional_roles": [{"id": "21", "name": "Водитель"}],
        "published_at": "2024-02-20T09:52:02+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "KZT", "from": 300000, "gross": False, "to": None},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": "Знание английского языка (B2). Хорошие знание "
            "города ПДД. Готовность к командировкам, в том "
            "числе за границу. Пунктуальность. ",
            "responsibility": "Мелкосрочный ремонт авто.",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93514566?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": {
            "building": "51А",
            "city": "Хабаровск",
            "description": None,
            "id": "4898993",
            "lat": 48.474997,
            "lng": 135.058846,
            "metro": None,
            "metro_stations": [],
            "raw": "Хабаровск, улица Истомина, 51А",
            "street": "улица Истомина",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93254580",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93254580",
        "archived": False,
        "area": {"id": "102", "name": "Хабаровск", "url": "https://api.hh.ru/areas/102"},
        "contacts": None,
        "created_at": "2024-02-15T08:00:54+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/4987434",
            "id": "4987434",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/4218361.jpeg",
                "90": "https://hhcdn.ru/employer-logo/4218360.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/944456.jpg",
            },
            "name": "Охотская Горно-Геологическая Компания",
            "trusted": True,
            "url": "https://api.hh.ru/employers/4987434",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=4987434",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
        "has_test": False,
        "id": "93254580",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Машинист буровой установки RU-75",
        "premium": False,
        "professional_roles": [{"id": "63", "name": "Машинист"}],
        "published_at": "2024-02-15T08:00:54+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 228000, "gross": False, "to": 228000},
        "schedule": {"id": "flyInFlyOut", "name": "Вахтовый метод"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Квалификационное удостоверение машиниста буровой "
            "установки 5 разряда. Опыт работы на буровой "
            "установки RU-75., LM-75. Проведение текущих "
            "аварийных и...",
            "responsibility": "Бурение из буровых камер. Бурение согласно "
            "ГТН, умение подобрать породоразрушающий "
            "инструмент, монтаж на устье скважины.",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93254580?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": True,
        "accept_temporary": False,
        "address": None,
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93545071",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93545071",
        "archived": False,
        "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
        "contacts": None,
        "created_at": "2024-02-20T14:19:36+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/2021156",
            "id": "2021156",
            "logo_urls": None,
            "name": "ТТО АМИК",
            "trusted": True,
            "url": "https://api.hh.ru/employers/2021156",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=2021156",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "moreThan6", "name": "Более 6 лет"},
        "has_test": False,
        "id": "93545071",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Семейный водитель",
        "premium": False,
        "professional_roles": [{"id": "21", "name": "Водитель"}],
        "published_at": "2024-02-20T14:19:36+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 120000, "gross": False, "to": 120000},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "snippet": {
            "requirement": "опыт работы профессиональным водителем от 10 "
            "лет, семейным водителем - от 5 лет. - наличие "
            "рекомендательных писем (обязательно). - "
            "спокойное,комфортное и безопасное...",
            "responsibility": "работа в качестве семейного водителя. - "
            "подача автомобиля по указанному месту в "
            "обозначенное время. - планирование "
            "оптимального маршрута движения. - выполнение "
            "поручений профессионального...",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93545071?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
    {
        "accept_incomplete_resumes": False,
        "accept_temporary": False,
        "address": {
            "building": "1к10",
            "city": "Казань",
            "description": None,
            "id": "15161689",
            "lat": 55.724135,
            "lng": 49.098078,
            "metro": None,
            "metro_stations": [],
            "raw": "Казань, Приволжский район, жилой массив Отары, Дорожная " "улица, 1к10",
            "street": "Приволжский район, жилой массив Отары, Дорожная " "улица",
        },
        "adv_context": None,
        "adv_response_url": None,
        "alternate_url": "https://hh.ru/vacancy/93161709",
        "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93161709",
        "archived": False,
        "area": {"id": "88", "name": "Казань", "url": "https://api.hh.ru/areas/88"},
        "contacts": None,
        "created_at": "2024-02-13T17:06:04+0300",
        "department": None,
        "employer": {
            "accredited_it_employer": False,
            "alternate_url": "https://hh.ru/employer/1060821",
            "id": "1060821",
            "logo_urls": {
                "240": "https://hhcdn.ru/employer-logo/874869.jpeg",
                "90": "https://hhcdn.ru/employer-logo/874868.jpeg",
                "original": "https://hhcdn.ru/employer-logo-original/85446.jpg",
            },
            "name": "Рост Развитие Решение",
            "trusted": True,
            "url": "https://api.hh.ru/employers/1060821",
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=1060821",
        },
        "employment": {"id": "full", "name": "Полная занятость"},
        "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
        "has_test": False,
        "id": "93161709",
        "insider_interview": None,
        "is_adv_vacancy": False,
        "name": "Менеджер по работе с клиентами (МЕРКАТОР)",
        "premium": False,
        "professional_roles": [{"id": "70", "name": "Менеджер по продажам, менеджер по работе с " "клиентами"}],
        "published_at": "2024-02-13T17:06:04+0300",
        "relations": [],
        "response_letter_required": False,
        "response_url": None,
        "salary": {"currency": "RUR", "from": 100000, "gross": True, "to": None},
        "schedule": {"id": "fullDay", "name": "Полный день"},
        "show_logo_in_search": None,
        "snippet": {
            "requirement": "Опыт в продажах или с клиентами. Грамотная речь. " "Активность. Коммуникабельность.",
            "responsibility": "Работа с клиентами. Контроль остатков "
            "инструмента на складе. Работа с дебиторской "
            "задолженностью. Отчетность в установленной "
            "форме (1С, Битрикс 24).",
        },
        "sort_point_distance": None,
        "type": {"id": "open", "name": "Открытая"},
        "url": "https://api.hh.ru/vacancies/93161709?host=hh.ru",
        "working_days": [],
        "working_time_intervals": [],
        "working_time_modes": [],
    },
]


def test_filter_word(data):
    assert filter_word(data, ["спокойное"]) == [
        {
            "accept_incomplete_resumes": True,
            "accept_temporary": False,
            "address": None,
            "adv_context": None,
            "adv_response_url": None,
            "alternate_url": "https://hh.ru/vacancy/93545071",
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=93545071",
            "archived": False,
            "area": {"id": "1", "name": "Москва", "url": "https://api.hh.ru/areas/1"},
            "contacts": None,
            "created_at": "2024-02-20T14:19:36+0300",
            "department": None,
            "employer": {
                "accredited_it_employer": False,
                "alternate_url": "https://hh.ru/employer/2021156",
                "id": "2021156",
                "logo_urls": None,
                "name": "ТТО АМИК",
                "trusted": True,
                "url": "https://api.hh.ru/employers/2021156",
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=2021156",
            },
            "employment": {"id": "full", "name": "Полная занятость"},
            "experience": {"id": "moreThan6", "name": "Более 6 лет"},
            "has_test": False,
            "id": "93545071",
            "insider_interview": None,
            "is_adv_vacancy": False,
            "name": "Семейный водитель",
            "premium": False,
            "professional_roles": [{"id": "21", "name": "Водитель"}],
            "published_at": "2024-02-20T14:19:36+0300",
            "relations": [],
            "response_letter_required": False,
            "response_url": None,
            "salary": {"currency": "RUR", "from": 120000, "gross": False, "to": 120000},
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "snippet": {
                "requirement": "опыт работы профессиональным водителем от 10 "
                "лет, семейным водителем - от 5 лет. - наличие "
                "рекомендательных писем (обязательно). - "
                "спокойное,комфортное и безопасное...",
                "responsibility": "работа в качестве семейного водителя. - "
                "подача автомобиля по указанному месту в "
                "обозначенное время. - планирование "
                "оптимального маршрута движения. - выполнение "
                "поручений профессионального...",
            },
            "sort_point_distance": None,
            "type": {"id": "open", "name": "Открытая"},
            "url": "https://api.hh.ru/vacancies/93545071?host=hh.ru",
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
        }
    ]
    assert filter_word(data, ["игра"]) == []
    assert filter_word(data, []) == data_1
